# Generated by Django 5.2.3 on 2025-07-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='name',
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='firebaseuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='firebaseuser',
            name='phone',
            field=models.CharField(blank=True, default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firebaseuser',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
