# Generated by Django 5.2.3 on 2025-07-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_firebaseuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='avatar',
        ),
    ]
