# Generated by Django 5.2.5 on 2025-08-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_registeruser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
