# Generated by Django 5.2.3 on 2025-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_direct_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
