# Generated by Django 5.2.3 on 2025-07-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcolorimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
