# Generated by Django 5.2.5 on 2025-09-14 11:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='image',
            field=models.ImageField(max_length=255, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='product_color_images/'),
        ),
    ]
